dubbo:
  application:
    name: dubbo-provider
  registry:
    address: localhost:2181
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30003
  monitor:
    protocol: register
  consumer:
    check: true
    timeout: 15000

server:
  port: 8080
