dubbo:
  application:
    name: dubbo-provider
  registry:
    address: localhost:2181
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30004
  monitor:
    protocol: register
  consumer:
    check: true
    timeout: 15000
  provider:
    # 4种默认轮询机制
    #  Random  RoundRobin  LeastActive ConsistentHash
    loadbalance: Random
    weight: 200

server:
  port: 8082
